site_name: Udacity BAND Wiki
site_description: Udacity BAND Wiki
site_author: Udacity & LI YAO
site_url: https://BANDVIP.github.io/BANDVIP_Tutorial/


# Copyright
copyright: 'Copyright &copy; 2019 Udacity LI YAO'

# Repository
repo_name: 'BANDVIP/BANDVIP_Tutorial'
repo_url: 'https://github.com/BANDVIP/BANDVIP_Tutorial'
edit_uri: 'blob/master/docs/'


# Contents
nav:
  - Induction:
    - Getting Started: index.md
    - 每周公开课摘要 : 0.md
    - 补充资料 : support.md
  - 导学文件:
    - Week1(1.16-1.20) 学前须知: 1.md
    - Week2(1.21-1.27) 可视化与信息有效表达: 2.md
    - Week3(1.28-2.3) 描述统计学: 3.md




# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'indigo'
    accent: 'red'
  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra_javascript:
  - 'https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - '_static/css/extra.css'
# markdown_extensions


markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
