site_name: Udacity BAND Wiki
site_description: Udacity BAND Wiki
site_author: Udacity & LI YAO
site_url: https://BANDVIP.github.io/BANDVIP_Tutorial/


# Copyright
copyright: 'Copyright &copy; 2019 Udacity LI YAO'

# Repository
repo_name: 'BANDVIP/BANDVIP_Tutorial'
repo_url: 'https://github.com/BANDVIP/BANDVIP_Tutorial'
edit_uri: 'blob/master/docs/'


# Contents
nav:
  - Induction:
    - Getting Started: index.md
    - 补充资料 : support.md
  - 导学文件:
    - Week1 学前须知: 1.md
    - Week2 可视化与信息有效表达: 2.md
    - Week3 描述统计学: 3.md
    - Week4 电子表格: 4.md
    - Week5 分析调查问卷: 5.md
    - Week6 商业分析问题解决框架: 8.md
    - Week7 Excel线性回归模型: 9.md
    - Week8 用Excel预测商业决策带来的收益增长: 10.md
    - Week9 毕业课程第一周: 11.md
    - Week10 毕业课程第二周: 12.md
    - Week11 毕业课程第三周: 13.md
    #- Week12(4.1-4.7) 毕业课程第二周: 12.md
    #- Week13(4.8-4.14) 毕业课程第三周: 13.md
    #- Week6(12.18-12.24) 推论统计学: 6.md
    #- Week7(12.25-12.31) A/B测试: 7.md


# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'indigo'
    accent: 'red'
  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra_javascript:
  - 'https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - '_static/css/extra.css'
# markdown_extensions


markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
